export const GROUPS = [
  {
    id: "digital_goods",
    label: "Gift cards / Video games / Xbox / Apple",
    shortLabel: "Games & gift cards",
    description: "Video game shops, CD keys, Apple/Xbox/PlayStation gift cards, and game top-up.",
    color: "#7c5cff",
  },
  {
    id: "esim",
    label: "eSIM",
    shortLabel: "eSIM",
    description: "eSIM and travel data plan sellers.",
    color: "#2ec9a0",
  },
  {
    id: "clothing",
    label: "Clothes",
    shortLabel: "Clothes",
    description: "Apparel, fashion, and clothing stores.",
    color: "#f0a14a",
  },
  {
    id: "hosting",
    label: "VPS / Servers",
    shortLabel: "VPS / Servers",
    description: "VPS, dedicated servers, and hosting providers.",
    color: "#4aa3ff",
  },
  {
    id: "proxies",
    label: "Proxies / ISP / Residential",
    shortLabel: "Proxies",
    description: "Residential, ISP, mobile, and datacenter proxy sellers.",
    color: "#3dd6d0",
  },
  {
    id: "gambling",
    label: "Casino / Gambling",
    shortLabel: "Casino",
    description: "Casinos, sportsbooks, and gambling sites.",
    color: "#ff5c7a",
  },
  {
    id: "donation",
    label: "Donation",
    shortLabel: "Donation",
    description: "Charity, fundraising, and donation pages.",
    color: "#9b7bff",
  },
];

export const UNKNOWN_GROUP = {
  id: "unknown",
  label: "Unknown / Other",
  shortLabel: "Unknown",
  description: "No strong match for the tracked seller groups.",
  color: "#8b93a7",
};

/** Weighted phrases. Longer / more specific terms score higher. */
export const SIGNALS = {
  digital_goods: [
    { term: "gift card", weight: 3 },
    { term: "gift cards", weight: 3 },
    { term: "giftcard", weight: 3 },
    { term: "giftcards", weight: 3 },
    { term: "apple gift card", weight: 8 },
    { term: "apple gift cards", weight: 8 },
    { term: "apple gift", weight: 6 },
    { term: "itunes gift", weight: 7 },
    { term: "itunes card", weight: 7 },
    { term: "app store gift", weight: 7 },
    { term: "apple store card", weight: 7 },
    { term: "xbox gift card", weight: 8 },
    { term: "xbox gift cards", weight: 8 },
    { term: "xbox gift", weight: 7 },
    { term: "xbox live", weight: 6 },
    { term: "xbox game pass", weight: 7 },
    { term: "microsoft gift", weight: 6 },
    { term: "playstation gift", weight: 7 },
    { term: "playstation card", weight: 7 },
    { term: "psn card", weight: 7 },
    { term: "psn gift", weight: 7 },
    { term: "ps plus", weight: 5 },
    { term: "nintendo eshop", weight: 6 },
    { term: "nintendo gift", weight: 6 },
    { term: "switch gift", weight: 5 },
    { term: "google play card", weight: 7 },
    { term: "google play gift", weight: 7 },
    { term: "steam gift", weight: 7 },
    { term: "steam wallet", weight: 7 },
    { term: "steam key", weight: 7 },
    { term: "steam keys", weight: 7 },
    { term: "video game", weight: 6 },
    { term: "video games", weight: 6 },
    { term: "videogame", weight: 6 },
    { term: "pc game", weight: 5 },
    { term: "pc games", weight: 5 },
    { term: "console game", weight: 5 },
    { term: "buy games", weight: 5 },
    { term: "game store", weight: 5 },
    { term: "digital game", weight: 6 },
    { term: "cd key", weight: 7 },
    { term: "cd keys", weight: 7 },
    { term: "cdkey", weight: 7 },
    { term: "cdkeys", weight: 7 },
    { term: "game key", weight: 6 },
    { term: "game keys", weight: 6 },
    { term: "activation key", weight: 5 },
    { term: "digital code", weight: 5 },
    { term: "digital codes", weight: 5 },
    { term: "prepaid card", weight: 2 },
    { term: "game top up", weight: 7 },
    { term: "game top-up", weight: 7 },
    { term: "game topup", weight: 7 },
    { term: "top-up", weight: 2 },
    { term: "top up", weight: 2 },
    { term: "topup", weight: 2 },
    { term: "in-game currency", weight: 5 },
    { term: "in game currency", weight: 5 },
    { term: "mobile legends", weight: 3 },
    { term: "pubg uc", weight: 5 },
    { term: "free fire diamond", weight: 5 },
    { term: "roblox gift", weight: 5 },
    { term: "robux", weight: 5 },
    { term: "valorant points", weight: 5 },
    { term: "v-bucks", weight: 6 },
    { term: "fortnite", weight: 3 },
    { term: "game credits", weight: 4 },
    { term: "instant gaming", weight: 6 },
    { term: "digital download", weight: 2 },
    { term: "software key", weight: 4 },
    { term: "license key", weight: 3 },
    { term: "kinguin", weight: 6 },
    { term: "eneba", weight: 5 },
    { term: "g2a", weight: 4 },
    { term: "gamivo", weight: 5 },
    { term: "hrkgame", weight: 5 },
    { term: "razer gold", weight: 5 },
    { term: "fanatical", weight: 5 },
    { term: "green man gaming", weight: 6 },
    { term: "humble bundle", weight: 5 },
    { term: "epic games", weight: 4 },
    { term: "battle.net", weight: 4 },
    { term: "playstation store", weight: 6 },
    { term: "xbox store", weight: 6 },
    { term: "nintendo switch", weight: 5 },
    { term: "ps5 games", weight: 6 },
    { term: "ps4 games", weight: 6 },
    { term: "xbox series", weight: 5 },
    { term: "redeem code", weight: 5 },
    { term: "product key", weight: 5 },
    { term: "game pin", weight: 5 },
    { term: "amazon gift card", weight: 6 },
    { term: "prepaid gaming", weight: 5 },
    { term: "digital game store", weight: 6 },
    { term: "v bucks", weight: 6 },
    { term: "league of legends", weight: 3 },
    { term: "genshin", weight: 3 },
    { term: "minecraft", weight: 3 },
    { term: "tarjeta de regalo", weight: 3 },
    { term: "tarjetas de regalo", weight: 3 },
    { term: "tarjeta regalo", weight: 3 },
    { term: "videojuegos", weight: 6 },
    { term: "tienda de juegos", weight: 6 },
    { term: "clave de juego", weight: 6 },
    { term: "claves de juego", weight: 6 },
    { term: "recarga de juegos", weight: 6 },
    { term: "juegos digitales", weight: 6 },
    { term: "carte cadeau", weight: 3 },
    { term: "cartes cadeaux", weight: 3 },
    { term: "jeux video", weight: 6 },
    { term: "jeu video", weight: 6 },
    { term: "boutique de jeux", weight: 6 },
    { term: "cle steam", weight: 6 },
    { term: "cles steam", weight: 6 },
    { term: "cle d activation", weight: 5 },
    { term: "recharge jeu", weight: 6 },
    { term: "jeux numeriques", weight: 5 },
    { term: "geschenkkarte", weight: 3 },
    { term: "geschenkkarten", weight: 3 },
    { term: "guthabenkarte", weight: 3 },
    { term: "videospiele", weight: 6 },
    { term: "spiele kaufen", weight: 6 },
    { term: "spieleschlussel", weight: 6 },
    { term: "spielkey", weight: 6 },
    { term: "produktschlussel", weight: 5 },
    { term: "cartao presente", weight: 3 },
    { term: "cartao-presente", weight: 3 },
    { term: "vale presente", weight: 3 },
    { term: "jogos digitais", weight: 6 },
    { term: "videogames", weight: 5 },
    { term: "chave de jogo", weight: 6 },
    { term: "recarga de jogos", weight: 6 },
    { term: "loja de jogos", weight: 5 },
    { term: "carta regalo", weight: 3 },
    { term: "buono regalo", weight: 3 },
    { term: "videogiochi", weight: 6 },
    { term: "chiave di gioco", weight: 6 },
    { term: "ricarica giochi", weight: 6 },
    { term: "cadeaukaart", weight: 3 },
    { term: "cadeaubon", weight: 3 },
    { term: "games kopen", weight: 5 },
    { term: "karta podarunkowa", weight: 3 },
    { term: "gry wideo", weight: 6 },
    { term: "gry cyfrowe", weight: 6 },
    { term: "klucz steam", weight: 6 },
    { term: "hediye karti", weight: 3 },
    { term: "hediye ceki", weight: 3 },
    { term: "video oyunlari", weight: 6 },
    { term: "oyun kodu", weight: 6 },
    { term: "steam kodu", weight: 6 },
    { term: "oyun yukleme", weight: 5 },
    { term: "oyun top up", weight: 6 },
    { term: "подарочная карта", weight: 3 },
    { term: "подарочные карты", weight: 3 },
    { term: "видеоигры", weight: 6 },
    { term: "игровой ключ", weight: 6 },
    { term: "ключи steam", weight: 6 },
    { term: "пополнение игр", weight: 6 },
    { term: "магазин игр", weight: 5 },
    { term: "بطاقة هدية", weight: 3 },
    { term: "بطاقات هدايا", weight: 3 },
    { term: "العاب فيديو", weight: 6 },
    { term: "ألعاب فيديو", weight: 6 },
    { term: "شحن الالعاب", weight: 6 },
    { term: "شحن الألعاب", weight: 6 },
    { term: "مفتاح ستيم", weight: 6 },
    { term: "礼品卡", weight: 3 },
    { term: "禮物卡", weight: 3 },
    { term: "游戏点卡", weight: 7 },
    { term: "游戏密钥", weight: 6 },
    { term: "游戏充值", weight: 7 },
    { term: "电子游戏", weight: 6 },
    { term: "数码游戏", weight: 5 },
    { term: "ギフトカード", weight: 3 },
    { term: "ビデオゲーム", weight: 6 },
    { term: "ゲームキー", weight: 6 },
    { term: "ゲームチャージ", weight: 6 },
    { term: "기프트카드", weight: 3 },
    { term: "상품권", weight: 3 },
    { term: "비디오 게임", weight: 6 },
    { term: "게임 충전", weight: 6 },
    { term: "게임 키", weight: 6 },
    { term: "kartu hadiah", weight: 3 },
    { term: "top up game", weight: 6 },
    { term: "voucher game", weight: 6 },
    { term: "the qua tang", weight: 3 },
    { term: "the qua tặng", weight: 3 },
    { term: "game ban quyen", weight: 5 },
  ],
  esim: [
    { term: "esim", weight: 8 },
    { term: "e-sim", weight: 8 },
    { term: "e sim", weight: 7 },
    { term: "travel esim", weight: 8 },
    { term: "data esim", weight: 7 },
    { term: "virtual sim", weight: 6 },
    { term: "qr code activation", weight: 5 },
    { term: "roaming data", weight: 5 },
    { term: "international data plan", weight: 6 },
    { term: "travel data plan", weight: 6 },
    { term: "mobile data plan", weight: 4 },
    { term: "airalo", weight: 7 },
    { term: "holafly", weight: 7 },
    { term: "nomad esim", weight: 7 },
    { term: "saily", weight: 4 },
    { term: "gigsky", weight: 5 },
    { term: "ubigi", weight: 5 },
    { term: "install esim", weight: 6 },
    { term: "activate esim", weight: 6 },
    { term: "esim store", weight: 7 },
    { term: "tarjeta esim", weight: 7 },
    { term: "carte esim", weight: 7 },
    { term: "esim kaufen", weight: 6 },
    { term: "اي سيم", weight: 6 },
    { term: "电子SIM", weight: 6 },
  ],
  clothing: [
    { term: "clothing", weight: 6 },
    { term: "clothes", weight: 6 },
    { term: "apparel", weight: 6 },
    { term: "fashion store", weight: 6 },
    { term: "fashion", weight: 3 },
    { term: "ready to wear", weight: 5 },
    { term: "ready-to-wear", weight: 5 },
    { term: "streetwear", weight: 6 },
    { term: "menswear", weight: 6 },
    { term: "womenswear", weight: 6 },
    { term: "t-shirt", weight: 4 },
    { term: "tshirt", weight: 4 },
    { term: "hoodie", weight: 4 },
    { term: "hoodies", weight: 4 },
    { term: "sneakers", weight: 4 },
    { term: "jeans", weight: 3 },
    { term: "dresses", weight: 4 },
    { term: "dress", weight: 2 },
    { term: "outerwear", weight: 5 },
    { term: "activewear", weight: 5 },
    { term: "lingerie", weight: 5 },
    { term: "boutique", weight: 3 },
    { term: "wardrobe", weight: 3 },
    { term: "size chart", weight: 3 },
    { term: "shop the look", weight: 4 },
    { term: "new arrivals", weight: 2 },
    { term: "collection", weight: 1 },
    { term: "shoes", weight: 3 },
    { term: "footwear", weight: 4 },
    { term: "jacket", weight: 3 },
    { term: "jackets", weight: 3 },
    { term: "shop men", weight: 3 },
    { term: "shop women", weight: 3 },
    { term: "kids clothing", weight: 5 },
    { term: "ropa", weight: 4 },
    { term: "vetements", weight: 5 },
    { term: "kleidung", weight: 5 },
    { term: "abbigliamento", weight: 5 },
    { term: "roupas", weight: 4 },
  ],
  hosting: [
    { term: "vps", weight: 8 },
    { term: "virtual private server", weight: 8 },
    { term: "dedicated server", weight: 7 },
    { term: "dedicated servers", weight: 7 },
    { term: "bare metal", weight: 6 },
    { term: "cloud vps", weight: 8 },
    { term: "vps hosting", weight: 8 },
    { term: "server hosting", weight: 6 },
    { term: "cloud hosting", weight: 5 },
    { term: "web hosting", weight: 4 },
    { term: "kvm vps", weight: 8 },
    { term: "rdp", weight: 4 },
    { term: "windows vps", weight: 7 },
    { term: "linux vps", weight: 7 },
    { term: "datacenter", weight: 4 },
    { term: "data center", weight: 4 },
    { term: "colocation", weight: 5 },
    { term: "colo", weight: 2 },
    { term: "proxmox", weight: 5 },
    { term: "cpanel", weight: 3 },
    { term: "managed server", weight: 5 },
    { term: "root access", weight: 3 },
    { term: "nvme vps", weight: 7 },
    { term: "hourly billing", weight: 2 },
  ],
  proxies: [
    { term: "residential proxy", weight: 8 },
    { term: "residential proxies", weight: 8 },
    { term: "resi proxy", weight: 7 },
    { term: "isp proxy", weight: 8 },
    { term: "isp proxies", weight: 8 },
    { term: "static isp", weight: 6 },
    { term: "isp ip", weight: 6 },
    { term: "mobile proxy", weight: 7 },
    { term: "mobile proxies", weight: 7 },
    { term: "datacenter proxy", weight: 7 },
    { term: "data center proxy", weight: 7 },
    { term: "rotating proxy", weight: 7 },
    { term: "rotating proxies", weight: 7 },
    { term: "socks5 proxy", weight: 7 },
    { term: "socks5", weight: 5 },
    { term: "http proxy", weight: 5 },
    { term: "https proxy", weight: 5 },
    { term: "proxy list", weight: 5 },
    { term: "buy proxies", weight: 7 },
    { term: "buy proxy", weight: 6 },
    { term: "proxy provider", weight: 6 },
    { term: "ip proxy", weight: 5 },
    { term: "residential ips", weight: 7 },
    { term: "residential ip", weight: 7 },
    { term: "sticky proxy", weight: 6 },
    { term: "backconnect proxy", weight: 6 },
    { term: "oxylabs", weight: 7 },
    { term: "brightdata", weight: 7 },
    { term: "bright data", weight: 7 },
    { term: "luminati", weight: 6 },
    { term: "smartproxy", weight: 7 },
    { term: "iproyal", weight: 7 },
    { term: "soax", weight: 5 },
    { term: "netnut", weight: 6 },
    { term: "webshare", weight: 5 },
    { term: "packetstream", weight: 6 },
    { term: "rayobyte", weight: 6 },
    { term: "proxy-seller", weight: 6 },
    { term: "proxy seller", weight: 6 },
    { term: "proxy residencial", weight: 8 },
    { term: "proxies residenciales", weight: 8 },
    { term: "proxy residentiel", weight: 8 },
    { term: "wohnproxy", weight: 6 },
    { term: "резидентные прокси", weight: 8 },
    { term: "прокси", weight: 4 },
    { term: "住宅代理", weight: 8 },
    { term: "住宅ip", weight: 7 },
    { term: "代理ip", weight: 6 },
  ],
  gambling: [
    { term: "online casino", weight: 8 },
    { term: "casino", weight: 6 },
    { term: "casinos", weight: 6 },
    { term: "gambling", weight: 7 },
    { term: "sportsbook", weight: 7 },
    { term: "sports betting", weight: 7 },
    { term: "online betting", weight: 7 },
    { term: "slot machine", weight: 6 },
    { term: "slots", weight: 4 },
    { term: "roulette", weight: 5 },
    { term: "blackjack", weight: 5 },
    { term: "poker", weight: 3 },
    { term: "jackpot", weight: 3 },
    { term: "wager", weight: 4 },
    { term: "place a bet", weight: 6 },
    { term: "live dealer", weight: 6 },
    { term: "odds", weight: 2 },
    { term: "betting site", weight: 7 },
    { term: "gamble", weight: 5 },
    { term: "responsible gambling", weight: 5 },
    { term: "18+", weight: 2 },
    { term: "spin the wheel", weight: 3 },
  ],
  donation: [
    { term: "donate now", weight: 8 },
    { term: "make a donation", weight: 8 },
    { term: "donation", weight: 6 },
    { term: "donations", weight: 6 },
    { term: "donate", weight: 5 },
    { term: "charity", weight: 6 },
    { term: "charitable", weight: 5 },
    { term: "nonprofit", weight: 5 },
    { term: "non-profit", weight: 5 },
    { term: "fundraising", weight: 6 },
    { term: "fundraiser", weight: 6 },
    { term: "gofundme", weight: 7 },
    { term: "patreon", weight: 4 },
    { term: "buy me a coffee", weight: 6 },
    { term: "support our cause", weight: 6 },
    { term: "give today", weight: 5 },
    { term: "tax deductible", weight: 5 },
    { term: "tax-deductible", weight: 5 },
    { term: "humanitarian", weight: 4 },
    { term: "volunteer", weight: 2 },
    { term: "crowdfunding", weight: 5 },
    { term: "sponsor a", weight: 3 },
    { term: "hacer una donacion", weight: 7 },
    { term: "faire un don", weight: 7 },
    { term: "spenden", weight: 5 },
    { term: "пожертвовать", weight: 6 },
    { term: "تبرع", weight: 6 },
  ],
};

/** Generic gift-card wording is not enough on its own — restaurants and hotels sell those too. */
export const GENERIC_DIGITAL_TERMS = new Set([
  "gift card",
  "gift cards",
  "giftcard",
  "giftcards",
  "prepaid card",
  "top-up",
  "top up",
  "topup",
  "tarjeta de regalo",
  "tarjetas de regalo",
  "tarjeta regalo",
  "carte cadeau",
  "cartes cadeaux",
  "geschenkkarte",
  "geschenkkarten",
  "guthabenkarte",
  "cartao presente",
  "cartao-presente",
  "vale presente",
  "carta regalo",
  "buono regalo",
  "cadeaukaart",
  "cadeaubon",
  "karta podarunkowa",
  "hediye karti",
  "hediye ceki",
  "подарочная карта",
  "подарочные карты",
  "بطاقة هدية",
  "بطاقات هدايا",
  "礼品卡",
  "禮物卡",
  "ギフトカード",
  "기프트카드",
  "상품권",
  "kartu hadiah",
  "the qua tang",
  "the qua tặng",
]);

/** Food, restaurant, and hotel pages that mention gift cards are not digital-goods shops. */
export const OFF_TOPIC_VETO = [
  { term: "restaurant", weight: 8 },
  { term: "restaurants", weight: 7 },
  { term: "restaurante", weight: 7 },
  { term: "ristorante", weight: 7 },
  { term: "restaurant gift card", weight: 12 },
  { term: "restaurant gift cards", weight: 12 },
  { term: "food menu", weight: 8 },
  { term: "dinner menu", weight: 8 },
  { term: "lunch menu", weight: 7 },
  { term: "our menu", weight: 6 },
  { term: "view menu", weight: 6 },
  { term: "order food", weight: 7 },
  { term: "order takeout", weight: 8 },
  { term: "takeout", weight: 6 },
  { term: "take-out", weight: 6 },
  { term: "takeaway", weight: 5 },
  { term: "dine in", weight: 7 },
  { term: "dine-in", weight: 7 },
  { term: "book a table", weight: 8 },
  { term: "reserve a table", weight: 8 },
  { term: "cuisine", weight: 6 },
  { term: "catering", weight: 6 },
  { term: "brunch", weight: 5 },
  { term: "appetizers", weight: 6 },
  { term: "appetizer", weight: 6 },
  { term: "entrees", weight: 6 },
  { term: "entree", weight: 5 },
  { term: "burritos", weight: 6 },
  { term: "burrito", weight: 5 },
  { term: "pizza", weight: 5 },
  { term: "pizzeria", weight: 7 },
  { term: "burgers", weight: 5 },
  { term: "steakhouse", weight: 7 },
  { term: "coffee shop", weight: 7 },
  { term: "bakery", weight: 5 },
  { term: "bistro", weight: 6 },
  { term: "tavern", weight: 5 },
  { term: "eatery", weight: 6 },
  { term: "food delivery", weight: 7 },
  { term: "doordash", weight: 5 },
  { term: "ubereats", weight: 5 },
  { term: "uber eats", weight: 5 },
  { term: "grubhub", weight: 5 },
  { term: "mexican food", weight: 7 },
  { term: "italian food", weight: 7 },
  { term: "chinese food", weight: 7 },
  { term: "fast food", weight: 7 },
  { term: "hotel", weight: 7 },
  { term: "hotels", weight: 7 },
  { term: "hotel gift card", weight: 12 },
  { term: "hotel gift cards", weight: 12 },
  { term: "resort", weight: 6 },
  { term: "resorts", weight: 6 },
  { term: "motel", weight: 6 },
  { term: "lodging", weight: 6 },
  { term: "accommodation", weight: 6 },
  { term: "accommodations", weight: 6 },
  { term: "book a room", weight: 8 },
  { term: "book your stay", weight: 8 },
  { term: "book a stay", weight: 8 },
  { term: "guest rooms", weight: 8 },
  { term: "guest room", weight: 7 },
  { term: "hotel rooms", weight: 8 },
  { term: "room rates", weight: 7 },
  { term: "nightly rate", weight: 7 },
  { term: "check-in", weight: 5 },
  { term: "concierge", weight: 6 },
  { term: "hospitality", weight: 4 },
  { term: "bed and breakfast", weight: 8 },
  { term: "vacation rental", weight: 7 },
  { term: "marriott", weight: 6 },
  { term: "hilton", weight: 6 },
  { term: "hyatt", weight: 6 },
  { term: "ihg", weight: 4 },
  { term: "airbnb", weight: 6 },
  { term: "booking.com", weight: 5 },
  { term: "tripadvisor", weight: 4 },
];

export function groupById(id) {
  return GROUPS.find((g) => g.id === id) ?? UNKNOWN_GROUP;
}
