export const GROUPS = [
  {
    id: "digital_goods",
    label: "Gift cards / Video games / Xbox / Apple",
    shortLabel: "Games & gift cards",
    description: "Video game shops, CD keys, Apple/Xbox/PlayStation gift cards, and game top-up.",
    color: "#7c5cff",
  },
  {
    id: "esim",
    label: "eSIM",
    shortLabel: "eSIM",
    description: "eSIM and travel data plan sellers.",
    color: "#2ec9a0",
  },
  {
    id: "clothing",
    label: "Clothes",
    shortLabel: "Clothes",
    description: "Apparel, fashion, and clothing stores.",
    color: "#f0a14a",
  },
  {
    id: "hosting",
    label: "VPS / Servers",
    shortLabel: "VPS / Servers",
    description: "VPS, dedicated servers, and hosting providers.",
    color: "#4aa3ff",
  },
  {
    id: "gambling",
    label: "Casino / Gambling",
    shortLabel: "Casino",
    description: "Casinos, sportsbooks, and gambling sites.",
    color: "#ff5c7a",
  },
  {
    id: "donation",
    label: "Donation",
    shortLabel: "Donation",
    description: "Charity, fundraising, and donation pages.",
    color: "#9b7bff",
  },
];

export const UNKNOWN_GROUP = {
  id: "unknown",
  label: "Unknown / Other",
  shortLabel: "Unknown",
  description: "No strong match for the tracked seller groups.",
  color: "#8b93a7",
};

/** Weighted phrases. Longer / more specific terms score higher. */
export const SIGNALS = {
  digital_goods: [
    { term: "gift card", weight: 6 },
    { term: "gift cards", weight: 6 },
    { term: "giftcard", weight: 6 },
    { term: "giftcards", weight: 6 },
    { term: "apple gift card", weight: 8 },
    { term: "apple gift cards", weight: 8 },
    { term: "apple gift", weight: 6 },
    { term: "itunes gift", weight: 7 },
    { term: "itunes card", weight: 7 },
    { term: "app store gift", weight: 7 },
    { term: "apple store card", weight: 7 },
    { term: "xbox gift card", weight: 8 },
    { term: "xbox gift cards", weight: 8 },
    { term: "xbox gift", weight: 7 },
    { term: "xbox live", weight: 6 },
    { term: "xbox game pass", weight: 7 },
    { term: "microsoft gift", weight: 6 },
    { term: "playstation gift", weight: 7 },
    { term: "playstation card", weight: 7 },
    { term: "psn card", weight: 7 },
    { term: "psn gift", weight: 7 },
    { term: "ps plus", weight: 5 },
    { term: "nintendo eshop", weight: 6 },
    { term: "nintendo gift", weight: 6 },
    { term: "switch gift", weight: 5 },
    { term: "google play card", weight: 7 },
    { term: "google play gift", weight: 7 },
    { term: "steam gift", weight: 7 },
    { term: "steam wallet", weight: 7 },
    { term: "steam key", weight: 7 },
    { term: "steam keys", weight: 7 },
    { term: "video game", weight: 6 },
    { term: "video games", weight: 6 },
    { term: "videogame", weight: 6 },
    { term: "pc game", weight: 5 },
    { term: "pc games", weight: 5 },
    { term: "console game", weight: 5 },
    { term: "buy games", weight: 5 },
    { term: "game store", weight: 5 },
    { term: "digital game", weight: 6 },
    { term: "cd key", weight: 7 },
    { term: "cd keys", weight: 7 },
    { term: "cdkey", weight: 7 },
    { term: "cdkeys", weight: 7 },
    { term: "game key", weight: 6 },
    { term: "game keys", weight: 6 },
    { term: "activation key", weight: 5 },
    { term: "digital code", weight: 5 },
    { term: "digital codes", weight: 5 },
    { term: "prepaid card", weight: 4 },
    { term: "game top up", weight: 7 },
    { term: "game top-up", weight: 7 },
    { term: "game topup", weight: 7 },
    { term: "top-up", weight: 4 },
    { term: "top up", weight: 3 },
    { term: "topup", weight: 4 },
    { term: "in-game currency", weight: 5 },
    { term: "in game currency", weight: 5 },
    { term: "mobile legends", weight: 3 },
    { term: "pubg uc", weight: 5 },
    { term: "free fire diamond", weight: 5 },
    { term: "roblox gift", weight: 5 },
    { term: "robux", weight: 5 },
    { term: "valorant points", weight: 5 },
    { term: "v-bucks", weight: 6 },
    { term: "fortnite", weight: 3 },
    { term: "game credits", weight: 4 },
    { term: "instant gaming", weight: 6 },
    { term: "digital download", weight: 2 },
    { term: "software key", weight: 4 },
    { term: "license key", weight: 3 },
    { term: "kinguin", weight: 6 },
    { term: "eneba", weight: 5 },
    { term: "g2a", weight: 4 },
    { term: "gamivo", weight: 5 },
    { term: "hrkgame", weight: 5 },
    { term: "razer gold", weight: 5 },
    { term: "fanatical", weight: 5 },
    { term: "green man gaming", weight: 6 },
    { term: "humble bundle", weight: 5 },
    { term: "epic games", weight: 4 },
    { term: "battle.net", weight: 4 },
    { term: "playstation store", weight: 6 },
    { term: "xbox store", weight: 6 },
    { term: "nintendo switch", weight: 5 },
    { term: "ps5 games", weight: 6 },
    { term: "ps4 games", weight: 6 },
    { term: "xbox series", weight: 5 },
    { term: "redeem code", weight: 5 },
    { term: "product key", weight: 5 },
    { term: "game pin", weight: 5 },
    { term: "amazon gift card", weight: 6 },
    { term: "prepaid gaming", weight: 5 },
    { term: "digital game store", weight: 6 },
    { term: "v bucks", weight: 6 },
    { term: "league of legends", weight: 3 },
    { term: "genshin", weight: 3 },
    { term: "minecraft", weight: 3 },
    { term: "tarjeta de regalo", weight: 7 },
    { term: "tarjetas de regalo", weight: 7 },
    { term: "tarjeta regalo", weight: 6 },
    { term: "videojuegos", weight: 6 },
    { term: "tienda de juegos", weight: 6 },
    { term: "clave de juego", weight: 6 },
    { term: "claves de juego", weight: 6 },
    { term: "recarga de juegos", weight: 6 },
    { term: "juegos digitales", weight: 6 },
    { term: "carte cadeau", weight: 7 },
    { term: "cartes cadeaux", weight: 7 },
    { term: "jeux video", weight: 6 },
    { term: "jeu video", weight: 6 },
    { term: "boutique de jeux", weight: 6 },
    { term: "cle steam", weight: 6 },
    { term: "cles steam", weight: 6 },
    { term: "cle d activation", weight: 5 },
    { term: "recharge jeu", weight: 6 },
    { term: "jeux numeriques", weight: 5 },
    { term: "geschenkkarte", weight: 7 },
    { term: "geschenkkarten", weight: 7 },
    { term: "guthabenkarte", weight: 6 },
    { term: "videospiele", weight: 6 },
    { term: "spiele kaufen", weight: 6 },
    { term: "spieleschlussel", weight: 6 },
    { term: "spielkey", weight: 6 },
    { term: "produktschlussel", weight: 5 },
    { term: "cartao presente", weight: 7 },
    { term: "cartao-presente", weight: 7 },
    { term: "vale presente", weight: 6 },
    { term: "jogos digitais", weight: 6 },
    { term: "videogames", weight: 5 },
    { term: "chave de jogo", weight: 6 },
    { term: "recarga de jogos", weight: 6 },
    { term: "loja de jogos", weight: 5 },
    { term: "carta regalo", weight: 7 },
    { term: "buono regalo", weight: 6 },
    { term: "videogiochi", weight: 6 },
    { term: "chiave di gioco", weight: 6 },
    { term: "ricarica giochi", weight: 6 },
    { term: "cadeaukaart", weight: 7 },
    { term: "cadeaubon", weight: 5 },
    { term: "games kopen", weight: 5 },
    { term: "karta podarunkowa", weight: 7 },
    { term: "gry wideo", weight: 6 },
    { term: "gry cyfrowe", weight: 6 },
    { term: "klucz steam", weight: 6 },
    { term: "hediye karti", weight: 7 },
    { term: "hediye ceki", weight: 6 },
    { term: "video oyunlari", weight: 6 },
    { term: "oyun kodu", weight: 6 },
    { term: "steam kodu", weight: 6 },
    { term: "oyun yukleme", weight: 5 },
    { term: "oyun top up", weight: 6 },
    { term: "подарочная карта", weight: 7 },
    { term: "подарочные карты", weight: 7 },
    { term: "видеоигры", weight: 6 },
    { term: "игровой ключ", weight: 6 },
    { term: "ключи steam", weight: 6 },
    { term: "пополнение игр", weight: 6 },
    { term: "магазин игр", weight: 5 },
    { term: "بطاقة هدية", weight: 7 },
    { term: "بطاقات هدايا", weight: 7 },
    { term: "العاب فيديو", weight: 6 },
    { term: "ألعاب فيديو", weight: 6 },
    { term: "شحن الالعاب", weight: 6 },
    { term: "شحن الألعاب", weight: 6 },
    { term: "مفتاح ستيم", weight: 6 },
    { term: "礼品卡", weight: 7 },
    { term: "禮物卡", weight: 7 },
    { term: "游戏点卡", weight: 7 },
    { term: "游戏密钥", weight: 6 },
    { term: "游戏充值", weight: 7 },
    { term: "电子游戏", weight: 6 },
    { term: "数码游戏", weight: 5 },
    { term: "ギフトカード", weight: 7 },
    { term: "ビデオゲーム", weight: 6 },
    { term: "ゲームキー", weight: 6 },
    { term: "ゲームチャージ", weight: 6 },
    { term: "기프트카드", weight: 7 },
    { term: "상품권", weight: 5 },
    { term: "비디오 게임", weight: 6 },
    { term: "게임 충전", weight: 6 },
    { term: "게임 키", weight: 6 },
    { term: "kartu hadiah", weight: 6 },
    { term: "top up game", weight: 6 },
    { term: "voucher game", weight: 6 },
    { term: "the qua tang", weight: 6 },
    { term: "the qua tặng", weight: 6 },
    { term: "game ban quyen", weight: 5 },
  ],
  esim: [
    { term: "esim", weight: 8 },
    { term: "e-sim", weight: 8 },
    { term: "e sim", weight: 7 },
    { term: "travel esim", weight: 8 },
    { term: "data esim", weight: 7 },
    { term: "virtual sim", weight: 6 },
    { term: "qr code activation", weight: 5 },
    { term: "roaming data", weight: 5 },
    { term: "international data plan", weight: 6 },
    { term: "travel data plan", weight: 6 },
    { term: "mobile data plan", weight: 4 },
    { term: "airalo", weight: 7 },
    { term: "holafly", weight: 7 },
    { term: "nomad esim", weight: 7 },
    { term: "saily", weight: 4 },
    { term: "gigsky", weight: 5 },
    { term: "ubigi", weight: 5 },
    { term: "install esim", weight: 6 },
    { term: "activate esim", weight: 6 },
    { term: "esim store", weight: 7 },
    { term: "tarjeta esim", weight: 7 },
    { term: "carte esim", weight: 7 },
    { term: "esim kaufen", weight: 6 },
    { term: "اي سيم", weight: 6 },
    { term: "电子SIM", weight: 6 },
  ],
  clothing: [
    { term: "clothing", weight: 6 },
    { term: "clothes", weight: 6 },
    { term: "apparel", weight: 6 },
    { term: "fashion store", weight: 6 },
    { term: "fashion", weight: 3 },
    { term: "ready to wear", weight: 5 },
    { term: "ready-to-wear", weight: 5 },
    { term: "streetwear", weight: 6 },
    { term: "menswear", weight: 6 },
    { term: "womenswear", weight: 6 },
    { term: "t-shirt", weight: 4 },
    { term: "tshirt", weight: 4 },
    { term: "hoodie", weight: 4 },
    { term: "hoodies", weight: 4 },
    { term: "sneakers", weight: 4 },
    { term: "jeans", weight: 3 },
    { term: "dresses", weight: 4 },
    { term: "dress", weight: 2 },
    { term: "outerwear", weight: 5 },
    { term: "activewear", weight: 5 },
    { term: "lingerie", weight: 5 },
    { term: "boutique", weight: 3 },
    { term: "wardrobe", weight: 3 },
    { term: "size chart", weight: 3 },
    { term: "shop the look", weight: 4 },
    { term: "new arrivals", weight: 2 },
    { term: "collection", weight: 1 },
    { term: "shoes", weight: 3 },
    { term: "footwear", weight: 4 },
    { term: "jacket", weight: 3 },
    { term: "jackets", weight: 3 },
    { term: "shop men", weight: 3 },
    { term: "shop women", weight: 3 },
    { term: "kids clothing", weight: 5 },
    { term: "ropa", weight: 4 },
    { term: "vetements", weight: 5 },
    { term: "kleidung", weight: 5 },
    { term: "abbigliamento", weight: 5 },
    { term: "roupas", weight: 4 },
  ],
  hosting: [
    { term: "vps", weight: 8 },
    { term: "virtual private server", weight: 8 },
    { term: "dedicated server", weight: 7 },
    { term: "dedicated servers", weight: 7 },
    { term: "bare metal", weight: 6 },
    { term: "cloud vps", weight: 8 },
    { term: "vps hosting", weight: 8 },
    { term: "server hosting", weight: 6 },
    { term: "cloud hosting", weight: 5 },
    { term: "web hosting", weight: 4 },
    { term: "kvm vps", weight: 8 },
    { term: "rdp", weight: 4 },
    { term: "windows vps", weight: 7 },
    { term: "linux vps", weight: 7 },
    { term: "datacenter", weight: 4 },
    { term: "data center", weight: 4 },
    { term: "colocation", weight: 5 },
    { term: "colo", weight: 2 },
    { term: "proxmox", weight: 5 },
    { term: "cpanel", weight: 3 },
    { term: "managed server", weight: 5 },
    { term: "root access", weight: 3 },
    { term: "nvme vps", weight: 7 },
    { term: "hourly billing", weight: 2 },
  ],
  gambling: [
    { term: "online casino", weight: 8 },
    { term: "casino", weight: 6 },
    { term: "casinos", weight: 6 },
    { term: "gambling", weight: 7 },
    { term: "sportsbook", weight: 7 },
    { term: "sports betting", weight: 7 },
    { term: "online betting", weight: 7 },
    { term: "slot machine", weight: 6 },
    { term: "slots", weight: 4 },
    { term: "roulette", weight: 5 },
    { term: "blackjack", weight: 5 },
    { term: "poker", weight: 3 },
    { term: "jackpot", weight: 3 },
    { term: "wager", weight: 4 },
    { term: "place a bet", weight: 6 },
    { term: "live dealer", weight: 6 },
    { term: "odds", weight: 2 },
    { term: "betting site", weight: 7 },
    { term: "gamble", weight: 5 },
    { term: "responsible gambling", weight: 5 },
    { term: "18+", weight: 2 },
    { term: "spin the wheel", weight: 3 },
  ],
  donation: [
    { term: "donate now", weight: 8 },
    { term: "make a donation", weight: 8 },
    { term: "donation", weight: 6 },
    { term: "donations", weight: 6 },
    { term: "donate", weight: 5 },
    { term: "charity", weight: 6 },
    { term: "charitable", weight: 5 },
    { term: "nonprofit", weight: 5 },
    { term: "non-profit", weight: 5 },
    { term: "fundraising", weight: 6 },
    { term: "fundraiser", weight: 6 },
    { term: "gofundme", weight: 7 },
    { term: "patreon", weight: 4 },
    { term: "buy me a coffee", weight: 6 },
    { term: "support our cause", weight: 6 },
    { term: "give today", weight: 5 },
    { term: "tax deductible", weight: 5 },
    { term: "tax-deductible", weight: 5 },
    { term: "humanitarian", weight: 4 },
    { term: "volunteer", weight: 2 },
    { term: "crowdfunding", weight: 5 },
    { term: "sponsor a", weight: 3 },
    { term: "hacer una donacion", weight: 7 },
    { term: "faire un don", weight: 7 },
    { term: "spenden", weight: 5 },
    { term: "пожертвовать", weight: 6 },
    { term: "تبرع", weight: 6 },
  ],
};

export function groupById(id) {
  return GROUPS.find((g) => g.id === id) ?? UNKNOWN_GROUP;
}
